/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view;

import modal.SubsDAO;
import modal.SubsModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Anzio
 */
public class AddSubscriptionForm extends javax.swing.JDialog {
    
    private SubsDAO subsDAO;
    private SimpleDateFormat dateFormat;

    /**
     * Creates new form AddSubscriptionForm
     */
    public AddSubscriptionForm(java.awt.Frame parent, boolean modal, SubsDAO subsDAO) {
        super(parent, modal);
        this.subsDAO = subsDAO;
        this.dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        initComponents();
        setLocationRelativeTo(parent);
        initializeForm();
    }
    
    /**
     * Inisialisasi form
     */
    private void initializeForm() {
        // Set combo box status
        cmbStatus.removeAllItems();
        cmbStatus.addItem("Aktif");
        cmbStatus.addItem("Tidak Aktif");
        cmbStatus.addItem("Expired");
        cmbStatus.setSelectedIndex(0); // Default ke "Aktif"
        
        // Set focus ke field KTP
        txtKTP.requestFocus();
    }
    
    /**
     * Validasi input form
     * @return true jika valid, false jika tidak valid
     */
    private boolean validateInput() {
        if (txtKTP.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "KTP tidak boleh kosong!");
            txtKTP.requestFocus();
            return false;
        }
        
        if (txtNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
            txtNama.requestFocus();
            return false;
        }
        
        if (txtTanggalExpired.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal expired tidak boleh kosong!");
            txtTanggalExpired.requestFocus();
            return false;
        }
        
        // Validasi format tanggal
        try {
            dateFormat.parse(txtTanggalExpired.getText().trim());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid! Gunakan format dd/MM/yyyy");
            txtTanggalExpired.requestFocus();
            return false;
        }
        
        // Cek apakah KTP sudah ada
        if (subsDAO.getSubscriptionByKTP(txtKTP.getText().trim()) != null) {
            JOptionPane.showMessageDialog(this, "KTP sudah terdaftar dalam sistem!");
            txtKTP.requestFocus();
            return false;
        }
        
        return true;
    }
    
    /**
     * Membersihkan semua field
     */
    private void clearFields() {
        txtKTP.setText("");
        txtNama.setText("");
        txtTanggalExpired.setText("");
        cmbStatus.setSelectedIndex(0);
        txtKTP.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKTP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        txtTanggalExpired = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Subscription");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Subscription");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setText("KTP:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Nama:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Status:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setText("Tanggal Expired (dd/MM/yyyy):");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtKTP.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(txtKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        txtNama.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        cmbStatus.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        txtTanggalExpired.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(txtTanggalExpired, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 80, -1));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 80, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (validateInput()) {
            try {
                // Buat object subscription baru
                SubsModel subscription = new SubsModel();
                subscription.setKtp(txtKTP.getText().trim());
                subscription.setNama(txtNama.getText().trim());
                subscription.setStatus(cmbStatus.getSelectedItem().toString());
                
                Date tanggalExpired = dateFormat.parse(txtTanggalExpired.getText().trim());
                subscription.setTanggalExpired(tanggalExpired);
                
                // Simpan ke database
                if (subsDAO.addSubscription(subscription)) {
                    JOptionPane.showMessageDialog(this, "Data subscription berhasil ditambahkan!");
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan data subscription!");
                }
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Error parsing tanggal: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearFields();
    }//GEN-LAST:event_btnResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtKTP;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTanggalExpired;
    // End of variables declaration//GEN-END:variables
}
