/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdminController;
import controller.BerlanggananController;
import model.BerlanggananDAO;
import model.BerlanggananModel;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anzio
 */
public class ListSubs extends javax.swing.JFrame {
    private BerlanggananDAO subsDAO;
    private DefaultTableModel tableModel;
    private AdminController adminControl;
    /**
     * Creates new form ListSubs
     */
    public ListSubs() {
        initComponents();
        initializeTable();
        subsDAO = new BerlanggananDAO();

    }

    /**
     * Inisialisasi struktur tabel
     */
    private void initializeTable() {
        String[] columnNames = {"KTP", "Nama", "Status", "Tanggal Expired"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Membuat tabel tidak dapat diedit langsung
            }
        };
        jTable1.setModel(tableModel);
        
        // Set lebar kolom
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(120); // KTP
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150); // Nama
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100); // Status
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(120); // Tanggal Expired
    }
    
    public void loadSubscriptionData() {
        // Bersihkan tabel terlebih dahulu
        tableModel.setRowCount(0);
        
        List<BerlanggananModel> subscriptions =  adminControl.loadSubs();
        if(subscriptions != null){
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

            for (BerlanggananModel sub : subscriptions) {
                Object[] rowData = {
                    sub.getKtp(),
                    sub.getNama(),
                    sub.getStatus(),
                    sub.getTanggalExpired() != null ? dateFormat.format(sub.getTanggalExpired()) : ""
                };
                tableModel.addRow(rowData);
            }

            // Update jumlah data di label
            jLabel1.setText("List Subs (" + subscriptions.size() + " data)");
        }
        
    }
     
            
    private BerlanggananModel getSelectedSubscription() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data subscription terlebih dahulu!");
            return null;
        }
        
        String ktp = (String) tableModel.getValueAt(selectedRow, 0);
        return subsDAO.getSubscriptionByKTP(ktp);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KTP", "Nama", "Status", "Tanggal Expired"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 270));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setText("Edit");
        jButton1.setMaximumSize(new java.awt.Dimension(123, 28));
        jButton1.setMinimumSize(new java.awt.Dimension(123, 28));
        jButton1.setPreferredSize(new java.awt.Dimension(123, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton2.setText("Kembali ke Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.setMaximumSize(new java.awt.Dimension(123, 28));
        jButton3.setMinimumSize(new java.awt.Dimension(123, 28));
        jButton3.setPreferredSize(new java.awt.Dimension(123, 28));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("List Subscription");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    //Edit List Subs
    BerlanggananModel selectedSub = getSelectedSubscription();
        if (selectedSub != null) {
            // Buka form edit subscription
            EditSubscriptionForm editForm = new EditSubscriptionForm(this, true, selectedSub, subsDAO);
            editForm.setVisible(true);
            
            // Refresh tabel setelah edit
            loadSubscriptionData();
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    //Kembali ke SubMenuB
        SubMenuB sm = adminControl.getSubMenuBView();
        sm.setVisible(true);
    
    // Menutup form saat ini (optional)
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    //hapus ListSubs
    BerlanggananModel selectedSub = getSelectedSubscription();
        if (selectedSub != null) {
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus subscription atas nama " + selectedSub.getNama() + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
            );
            
            if (confirm == JOptionPane.YES_OPTION) {
                if (subsDAO.deleteSubscription(selectedSub.getKtp())) {
                    JOptionPane.showMessageDialog(this, "Subscription berhasil dihapus!");
                    loadSubscriptionData(); // Refresh tabel
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus subscription!");
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListSubs().setVisible(true);
            }
        });
    }
    public void setController(AdminController controller) {
        this.adminControl = controller;
        //loadSubscriptionData();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
